/**
 * Style Dictionary v4 config
 * Transforms design tokens → CSS custom properties + TypeScript
 *
 * Token tiers:
 *   tokens/core/       → primitive values (color.primary.500)
 *   tokens/semantic/   → semantic aliases (color.action.primary.default)
 *   tokens/component/  → component tokens (component.button.borderRadius)
 *
 * Outputs:
 *   dist/tokens.css          → CSS custom properties (all tiers, flat)
 *   dist/tokens.dark.css     → dark mode overrides (semantic layer only)
 *   dist/tokens.js           → ESM JS object (runtime token access)
 *   dist/tokens.d.ts         → TypeScript declarations
 *   dist/tokens.scss         → SCSS variables (optional)
 */

import StyleDictionary from 'style-dictionary';

// ─── Custom transforms ────────────────────────────────────────────────────────

/**
 * px transform — converts raw numbers to px strings.
 *
 * NOTE: this project stores dimension values as numeric strings in the JSON
 * (e.g. "12", not 12), so the filter checks whether the value is numeric
 * rather than requiring typeof === 'number' — that check never matched
 * anything, which meant every spacing/sizing/borderRadius/borderWidth/
 * fontSize token was emitted unitless (e.g. "12" instead of "12px"), an
 * invalid CSS value that gets silently dropped by the browser.
 *
 * lineHeights is intentionally excluded — it must stay unitless (a ratio,
 * not a length) and is handled separately by the ds/lineHeight transform
 * below. Including it here as well would re-append "px" after that
 * transform already ran.
 */
StyleDictionary.registerTransform({
  name: 'ds/px',
  type: 'value',
  filter: (token) =>
    ['spacing', 'sizing', 'fontSizes', 'borderRadius', 'borderWidth'].includes(token.type) &&
    token.value !== '' &&
    token.value !== undefined &&
    !Number.isNaN(Number(token.value)),
  transform: (token) => `${token.value}px`,
});

/**
 * em transform — letter spacing stays in em, already a string.
 */
StyleDictionary.registerTransform({
  name: 'ds/letterSpacing',
  type: 'value',
  filter: (token) => token.type === 'letterSpacing',
  transform: (token) =>
    typeof token.value === 'number' ? `${token.value}em` : token.value,
});

/**
 * font-family quoting — wrap multi-word family names in quotes.
 */
StyleDictionary.registerTransform({
  name: 'ds/fontFamily',
  type: 'value',
  filter: (token) => token.type === 'fontFamilies',
  transform: (token) => token.value, // already a full stack string
});

/**
 * line-height — if value is a unitless ratio (e.g. 1.5), keep it unitless.
 */
StyleDictionary.registerTransform({
  name: 'ds/lineHeight',
  type: 'value',
  filter: (token) => token.type === 'lineHeights',
  transform: (token) =>
    typeof token.value === 'string' ? token.value : String(token.value),
});

// ─── Custom formats ───────────────────────────────────────────────────────────

/**
 * TypeScript declarations format.
 * Emits a typed const object + a Tokens type alias.
 */
StyleDictionary.registerFormat({
  name: 'ds/typescript/declarations',
  format: ({ dictionary }) => {
    const buildObject = (tokens) => {
      const obj = {};
      for (const token of tokens) {
        const parts = token.path;
        let cursor = obj;
        for (let i = 0; i < parts.length - 1; i++) {
          cursor[parts[i]] ??= {};
          cursor = cursor[parts[i]];
        }
        cursor[parts[parts.length - 1]] = token.value;
      }
      return obj;
    };

    const obj = buildObject(dictionary.allTokens);
    const json = JSON.stringify(obj, null, 2);

    return [
      '// Auto-generated by Style Dictionary. Do not edit.',
      '// Source: tokens/ directory — edit JSON files there.',
      '',
      `export const tokens = ${json} as const;`,
      '',
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
});

/**
 * ESM JS format.
 * Same shape as the TS format but plain JS, importable at runtime.
 */
StyleDictionary.registerFormat({
  name: 'ds/esm/module',
  format: ({ dictionary }) => {
    const buildObject = (tokens) => {
      const obj = {};
      for (const token of tokens) {
        const parts = token.path;
        let cursor = obj;
        for (let i = 0; i < parts.length - 1; i++) {
          cursor[parts[i]] ??= {};
          cursor = cursor[parts[i]];
        }
        cursor[parts[parts.length - 1]] = token.value;
      }
      return obj;
    };

    const obj = buildObject(dictionary.allTokens);
    const json = JSON.stringify(obj, null, 2);

    return [
      '// Auto-generated by Style Dictionary. Do not edit.',
      `export const tokens = ${json};`,
      'export default tokens;',
      '',
    ].join('\n');
  },
});

/**
 * Dark mode CSS format.
 * Emits only semantic color tokens that have a `dark` property defined,
 * wrapped in a `[data-theme="dark"]` selector (and prefers-color-scheme).
 *
 * Usage: add `data-theme="dark"` to <html> for JS-toggled dark mode,
 * or rely on the media query for OS-level preference.
 */
StyleDictionary.registerFormat({
  name: 'ds/css/dark-mode',
  format: ({ dictionary }) => {
    const darkTokens = dictionary.allTokens.filter(
      (t) => t.darkValue !== undefined,
    );

    if (darkTokens.length === 0) {
      return '/* No dark mode overrides defined yet. */\n';
    }

    const vars = darkTokens
      .map((t) => `  --${t.name}: ${t.darkValue};`)
      .join('\n');

    return [
      '/* Auto-generated dark mode overrides. Do not edit. */',
      '[data-theme="dark"] {',
      vars,
      '}',
      '',
      '@media (prefers-color-scheme: dark) {',
      '  :root:not([data-theme="light"]) {',
      vars.replace(/^/gm, '  '),
      '  }',
      '}',
      '',
    ].join('\n');
  },
});

// ─── Transform group ──────────────────────────────────────────────────────────

StyleDictionary.registerTransformGroup({
  name: 'ds/css',
  transforms: [
    'attribute/cti',
    'name/kebab',          // color-primary-500
    'ds/px',
    'ds/lineHeight',
    'ds/letterSpacing',
    'ds/fontFamily',
    'color/css',           // resolves hex + rgba
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'ds/ts',
  transforms: [
    'attribute/cti',
    'name/camel',          // colorPrimary500
    'ds/px',
    'ds/lineHeight',
    'ds/letterSpacing',
    'ds/fontFamily',
    'color/css',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'ds/scss',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'ds/px',
    'ds/lineHeight',
    'ds/letterSpacing',
    'ds/fontFamily',
    'color/css',
  ],
});

// ─── Main build ───────────────────────────────────────────────────────────────

const sd = new StyleDictionary({
  // Resolve token references across all three tiers in order:
  // core first so semantic can reference it, component last.
  source: [
    'tokens/core/**/*.json',
    'tokens/semantic/**/*.json',
    'tokens/component/**/*.json',
  ],

  // Global reference resolution — handles {color.primary.500} syntax
  usesDtcg: false, // set true if you migrate to DTCG $value/$type format

  platforms: {

    // ── 1. CSS custom properties ────────────────────────────────────────────
    css: {
      transformGroup: 'ds/css',
      prefix: '',           // --color-primary-500 (no extra prefix needed)
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: false, // flatten all references to resolved values
            showFileHeader: true,
          },
        },
      ],
    },

    // ── 2. CSS — semantic layer only (for scoped theming) ──────────────────
    'css/semantic': {
      transformGroup: 'ds/css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.semantic.css',
          format: 'css/variables',
          filter: (token) => token.filePath.includes('semantic'),
          options: {
            selector: ':root',
            outputReferences: true, // keep var(--color-primary-500) references
            showFileHeader: true,
          },
        },
      ],
    },

    // ── 3. Dark mode overrides ──────────────────────────────────────────────
    // NOTE: previously filtered to `filePath.includes('semantic')`, which
    // silently dropped every component-tier darkValue (including ones set
    // on Button/Checkbox/Toggle/ListItem/SectionHeader from the very first
    // session) — dark mode never actually reached any `--component-*`
    // variable. The `ds/css/dark-mode` format already restricts itself to
    // tokens with a `darkValue` defined, so no outer filter is needed here;
    // removing it lets both semantic- and component-tier overrides through.
    'css/dark': {
      transformGroup: 'ds/css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.dark.css',
          format: 'ds/css/dark-mode',
        },
      ],
    },

    // ── 4. SCSS variables ───────────────────────────────────────────────────
    scss: {
      transformGroup: 'ds/scss',
      buildPath: 'dist/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/variables',
          options: {
            outputReferences: false,
            showFileHeader: true,
          },
        },
      ],
    },

    // ── 5. ESM JS module ────────────────────────────────────────────────────
    js: {
      transformGroup: 'ds/ts',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'ds/esm/module',
        },
      ],
    },

    // ── 6. TypeScript declarations ──────────────────────────────────────────
    ts: {
      transformGroup: 'ds/ts',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.d.ts',
          format: 'ds/typescript/declarations',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log('\n✅ Token build complete → dist/');
